# Project information
site_name: argilla-python
site_url: https://argilla-io.github.io/argilla-python
site_author: Argilla, Inc.
site_description: The Argilla python server SDK

# Repository
repo_name: argilla-io/argilla-python
repo_url: https://github.com/argilla-io/argilla-python

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  # NOTE: Should we add some here?
  # logo: assets/logo.svg
  # favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src/argilla_sdk

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  # activating permalink: true makes the anchor link works in the notebooks
  - toc:
      permalink: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  - social
  - mknotebooks

nav:
  - Getting started: index.md