# Project information
site_name: Argilla
site_url: https://argilla-io.github.io/argilla-python
site_author: Argilla, Inc.
site_description: The Argilla python server SDK
copyright: Copyright &copy; 2017 - 2024 Argilla

# Repository
repo_name: argilla-io/argilla-python
repo_url: https://github.com/argilla-io/argilla-python

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/argilla-io
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/argilla_io
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCAIz8TmvQQrLqbD7sd-5S2A
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/rubrixworkspace/shared_invite/zt-20wllqq29-Z11~kp2SeFYjJ0qevJRiPg

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo-dark-mode.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src/argilla_sdk

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # activating permalink: true makes the anchor link works in the notebooks
  - toc:
      permalink: true


plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  - social
  - mknotebooks
  - tags:
      tags_file: tutorials/index.md


nav:
  - Overview:
    - index.md
    - Quickstart (WIP): overview/quickstart.md
    - Installation (WIP):
      - overview/installation/index.md
      - Python SDK: overview/installation/telemetry.md
      - FastAPI Server:
        - overview/installation/telemetry.md
    - Concepts (WIP):
      - overview/concepts/index.md
    - Changelog (WIP): overview/changelog.md
    - Contributing:
      - GitHub workflows: overview/community/contributor.md
      - Development environment: overview/community/developer.md
    - Community: overview/community/index.md
    - FAQ: overview/faq.md
  - How-to guides:
    - how_to_guides/index.md
    - Manage users, credentials, and workspaces:
      - how_to_guides/team/index.md
      - Users: how_to_guides/team/user.md
      - Workspaces: how_to_guides/team/workspace.md
    - Manage and create datasets:
      - how_to_guides/dataset/index.md
      - Datasets: how_to_guides/dataset/dataset.md
      - Dataset settings: how_to_guides/dataset/settings.md
    - Add, update, and delete records: how_to_guides/record.md
    - Query, filter and export records: how_to_guides/query_export.md
    # - Distribute annotation work: how_to_guides/distribute.md
    # - Compute metrics and KPIs:
    #   - how_to_guides/metrics/index.md
    #   - Dataset progress: how_to_guides/metrics/dataset.md
    #   - Model performance: how_to_guides/metrics/model.md
    #   - Annotator performance: how_to_guides/metrics/annotator.md
    # - Fine-tune a model: fine_tune.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/rag_llm.md
    - tutorials/rag_rankers_and_retrievers.md
  - Integrations:
    - integrations/index.md
  - API Reference:
    - Python SDK: reference/
    - FastAPI Server: reference/
