# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Test and build the `argilla-sdk` python package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    services:
      argilla-quickstart:
        image: argilla/argilla-quickstart:main
        ports:
          - 6900:6900
        env:
          ANNOTATOR_USERNAME: annotator
          OWNER_USERNAME: argilla
          OWNER_API_KEY: argilla.apikey
          ADMIN_USERNAME: admin
          ADMIN_API_KEY: admin.apikey
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          pdm install
      - name: Wait for argilla-quickstart to start
        run: |
          while ! nc -z localhost 6900; do sleep 1; done
      - name: Run tests
        run: |
          pdm run test
