name: Publish documentation

on:
  push:
    branches:
      - main
      - gh-pages
    tags:
      - "**"

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - docs/**
      - ci/**

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:

      - name: checkout docs-site
        uses: actions/checkout@v4

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          pdm install

      - name: Set git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: pdm run mike deploy dev --push
        if: github.ref == 'refs/heads/main'

      - run: pdm run mike deploy ${{ github.ref_name }} latest --update-aliases --push
        if: startsWith(github.head_ref, 'refs/tags/')

      - run: pdm run mike deploy $GITHUB_REF_NAME --push
        if: startsWith(github.head_ref, 'refs/head/docs/')
